# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('contact', models.CharField(max_length=32)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'participants',
            },
        ),
    ]
