# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
    ]
