# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160128_1514'),
        ('events', '0004_remove_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
