# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 28, 16, 13, 32, 567000)),
        ),
    ]
