# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20160128_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
