# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=1988, verbose_name=datetime.date(2016, 1, 29)),
            preserve_default=False,
        ),
    ]
