# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20160129_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='game',
        ),
        migrations.RemoveField(
            model_name='event',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
    ]
