# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(default='none', max_length=100)),
                ('street2', models.CharField(default='none', max_length=100)),
                ('city', models.CharField(default='none', max_length=100)),
                ('state', models.CharField(default='none', max_length=2)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='Bio is not Set', max_length=200)),
                ('games', models.ManyToManyField(to='games.Game')),
                ('info_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by', to='accounts.Info')),
                ('review_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for', to='accounts.Info')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='info',
            name='reviews',
            field=models.ManyToManyField(related_name='related_to', through='accounts.Review', to='accounts.Info'),
        ),
        migrations.AddField(
            model_name='info',
            name='user_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address'),
        ),
    ]
