# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('games', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'infos',
            },
        ),
    ]
