# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160128_1514'),
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='city',
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(default=''),
        ),
        migrations.RemoveField(
            model_name='info',
            name='games',
        ),
        migrations.AddField(
            model_name='info',
            name='games',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
