# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20160129_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by', to=settings.AUTH_USER_MODEL)),
                ('review_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='reviews',
            field=models.ManyToManyField(related_name='related_to', through='accounts.Review', to='accounts.Info'),
        ),
    ]
