# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160130_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by', to='accounts.Info'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for', to='accounts.Info'),
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
