# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.TextField(max_length=255)),
                ('game_image', models.CharField(max_length=255)),
                ('game_description', models.TextField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('game_length', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('game_title',),
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=50)),
                ('category_description', models.TextField()),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ManyToManyField(to='games.GameType'),
        ),
    ]
