# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
        migrations.AlterModelTable(
            name='gametype',
            table='gametypes',
        ),
    ]
