# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160128_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.FloatField(),
        ),
    ]
