# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160129_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(),
        ),
    ]
