# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160129_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(),
        ),
    ]
