# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160130_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street2',
        ),
    ]
